### ISSUE TITLE
Flashcard [Add, delete, update, read]

### ISSUE THREAD

**Issue by Ducnguyen147** [BetterFlashcards/BF-Frontend#1]
User should be able to see a list of all flashcards in a specific deck from
List should contain front facing word, ?
User should be able to search and sort the list based on different properties (alphabetical, addition date)
User should be presented with an empty state if the list is empty
User should be presented with an error view if any error occurs while fetching the list (e.g. network unavailable)

**Comment by Khalilove666** [comment]
implemented
