### ISSUE TITLE
List all decks [Add, delete, update, read]

### ISSUE THREAD

**Issue by Ducnguyen147** [BetterFlashcards/BF-Frontend#2]
User should be able to see a list of all their decks
    List should contain deck title, number of flashcards in deck, latest update, etc
    User should be able to search and sort the list based on different properties
    User should be presented with an empty state if the list is empty
    User should be presented with an error view if any error occurs while fetching the list (e.g. network unavailable)

**Comment by Khalilove666** [comment]
implemented
