### ISSUE TITLE
Draft flashcard [Add, delete, update, read]

### ISSUE THREAD

**Issue by Ducnguyen147** [BetterFlashcards/BF-Frontend#3]
1. User should be able to see list of flashcards they started to create but didn’t finish (referred to as Draft flashcards)
2. Draft flashcards shouldn’t show up when practicing
3. User should be able to continue creation process of a draft flashcard (including load translation, pick translation, manual entry, deck selection)
4. User should be able to delete a draft flashcard

**Comment by Khalilove666** [comment]
implemented
