### ISSUE TITLE
Practice screen for web version

### ISSUE THREAD

**Issue by Ducnguyen147** [BetterFlashcards/BF-Frontend#4]
This task targets the design and implementation of a practice page for flashcards, integrating the spaced repetition method. The page will display flashcards from a selected deck in a specific order, allowing users to interact with them one at a time.

Key Features:

- Flashcard Display: The page will display one flashcard at a time.

- Front Side First: Initially, only the front side of the flashcard will be visible.

- Reveal Back Side: Users can reveal the back side of the flashcard by clicking on it.

- Feedback Mechanism: Users can provide feedback on their knowledge of the flashcard content.

- Button Feedback: Optionally, buttons can be provided for users to indicate whether they know or don't know the answer on the flashcard.

- Swipe Feedback: Users can also swipe left if they don't know the answer, or swipe right if they do.

- Spaced Repetition Integration: The flashcards will be presented in a specific order according to the spaced repetition method, optimizing learning efficiency.

By incorporating these features, the practice page will facilitate effective and efficient learning through spaced repetition and user feedback.

**Comment by Khalilove666** [comment]
implemented
