### ISSUE TITLE
Login/ Logout feature for web version

### ISSUE THREAD

**Issue by Ducnguyen147** [BetterFlashcards/BF-Frontend#7]
Login:
User is presented with a username, password field and login button
If user types existing username and password, taps the login button: user is logged into the app 
If the user types invalid login information, an appropriate error is shown
There's a button to switch to Registration

Registration:
User is presented with a username, password field and register button
If user types unique username and acceptable password, taps the register button: New account is created, user is logged into the app 
If the user types an existing username, an error is shown
If the user types a password that doesn't match the password policy, an error is shown
There's a button to switch to Login

**Comment by Khalilove666** [comment]
implemented
